sonar.sources=app,routes,database
sonar.tests=tests
sonar.test.inclusions=tests/**/*.php
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**
sonar.coverage.exclusions=database/**,routes/**,app/Models/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
