@extends('layouts.app')
@section('content')
<header class="profile-hero"><a class="back-link" href="{{ route('profiles.index') }}">← Jogadores</a><div class="profile-title"><span class="profile-avatar large">{{ $profile->avatar ?: mb_strtoupper(mb_substr($profile->nickname,0,1)) }}</span><div><span class="eyebrow">Perfil do jogador</span><h1>{{ $profile->nickname }}</h1><p>{{ $profile->preferred_deck_name ?: 'Deck não informado' }} @if($profile->preferred_deck_colors) · {{ $profile->preferred_deck_colors }} @endif</p></div></div>
<form method="POST" action="{{ route('profiles.friend',$profile) }}">@csrf @method('PATCH')<button class="btn {{ $profile->is_friend ? 'btn-secondary' : 'btn-primary' }}">{{ $profile->is_friend ? '★ Amigo salvo' : 'Adicionar aos amigos' }}</button></form></header>
<div class="stat-grid"><article class="card stat-card"><b>{{ $summary['wins'] }}–{{ $summary['losses'] }}</b><span>Vitórias / derrotas</span></article><article class="card stat-card"><b>{{ $summary['games_for'] }}–{{ $summary['games_against'] }}</b><span>Games</span></article><article class="card stat-card"><b>{{ $summary['winrate'] }}%</b><span>Aproveitamento</span></article><article class="card stat-card"><b>{{ $summary['best_streak'] }}</b><span>Maior sequência</span></article></div>
<section class="card section-card"><span class="eyebrow">Badges desbloqueadas</span><h2>Conquistas</h2><div class="achievement-grid">@forelse($summary['achievements'] as $achievement)<article class="achievement"><span>{{ $achievement['icon'] }}</span><div><strong>{{ $achievement['name'] }}</strong><small>{{ $achievement['description'] }}</small></div></article>@empty<p class="muted">As primeiras conquistas chegam com os resultados.</p>@endforelse</div></section>
<div class="profile-columns"><section class="card section-card"><span class="eyebrow">Arsenal</span><h2>Decks usados</h2>@forelse($summary['decks'] as $deck)<div class="history-row"><div><strong>{{ $deck['name'] }}</strong><small>{{ $deck['colors'] ?: 'Cores não informadas' }}</small></div><b>{{ $deck['wins'] }}W — {{ $deck['losses'] }}L</b></div>@empty<p class="muted">Nenhum deck registrado.</p>@endforelse</section>
<section class="card section-card"><span class="eyebrow">Histórico</span><h2>Campeonatos</h2>@forelse($summary['tournaments'] as $tournament)<a class="history-row" href="{{ route('tournaments.show',$tournament) }}"><div><strong>{{ $tournament->name }}</strong><small>{{ $tournament->tournament_date?->format('d/m/Y') }}</small></div><span>→</span></a>@empty<p class="muted">Nenhum torneio disputado.</p>@endforelse</section></div>
@endsection
